# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://javierselva.github.io"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############
lang: "en"
timezone: "Europe/Madrid"
author: "Javier Selva"
title: "Javier Selva Castelló"
head_title: "Javier Selva's Personal Site"
description: "Website and blog of Javier Selva."
keywords: "selva, javier, personal, academic, ai, research, deep learning, machine learning"
favicon: "/assets/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/assets/img/computer.ico"


# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "/assets/img/me.png"
social_img: "/assets/img/social/"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
########
# Blog #
########
post-preview-words: 50
paginate: 8
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False
disqus-shortname: "personal-jekyll-theme"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"
# First image of the Timeline
timeline-img: "/img/timeline/default.png"
###########
# Contact #
###########
email: "your@email.here"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "Javier Selva has a background of computer science and currently specializes in Machine Learning. In particular he is passionate about NLP, CV and self-supervised learning with Transformers."
author_blurb_image: "/assets/img/me.png"
##################
# Social Buttons #
##################
social:
  - icon: "x-twitter"
    url: "https://twitter.com/javier_selvac"
  - icon: "github"
    url: "https://github.com/javierselva"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/javier-selva-castell%C3%B3-399738134/"
  - icon: "google-scholar"
    url: "https://scholar.google.com/citations?user=T5-DYyUAAAAJ"
  - icon: "youtube"
    url: "https://www.youtube.com/@javierselva509/featured"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  Papers: "latest-paper"
  Blog: "latest-post"

section_list:
  Papers: "publications"
  Blog: "blog"
  About: "about"

# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
collections:
  blog:
    permalink: "/blog/:path"
    paginate_path: "/blog/page:num/"
  publications:
    permalink: "/publications/:path"
    paginate_path: "/publications/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
